config/routes.rb
HubHub::Application.routes.draw do
  root 'home#index'

  get '/admin/sign_in', to: 'sessions#new', as: 'new_admin_session'
  post '/admin/sign_in', to: 'sessions#create', as: 'admin_sessions'
  delete '/admin/sign_out', to: 'sessions#destroy', as: 'destroy_admin_session'

  ActiveAdmin.routes(self)

  namespace :api, defaults: { format: 'json' } do
    resources :spokes, only: %i[index show]
    resources :posts, except: %i[new edit]
    resources :responses, except: %i[new edit]

    post '/sessions', to: 'sessions#create'
    delete '/sessions', to: 'sessions#destroy'

    resources :users, only: %i[create show update destroy]
  end
end

app/models/spoke.rb
class Spoke < ActiveRecord::Base
  has_many :posts, dependent: :destroy

  validates_presence_of :name
  validates_uniqueness_of :name
end

app/controllers/api/spokes_controller.rb
module Api
  class SpokesController < ApiController
    before_action :set_spoke, only: %i[show]

    # GET /spokes
    def index
      @spokes = Spoke.includes(:posts)
      respond_with :api, @spokes
    end

    # GET /spokes/1
    def show
      respond_with :api, @spoke
    end

    private

    # Use callbacks to share common setup or constraints between actions.
    def set_spoke
      @spoke = Spoke.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def spoke_params
      params.require(:spoke).permit(:name, :description)
    end
  end
end

app/helpers/api/spokes_helper.rb
module Api
  module SpokesHelper
    def html_rules_for_posting
      'Basic HTML is allowed here: formatting tags, links, and lists.'
    end
  end
end

app/views/spokes/_post_link_modal.html.haml
.modal.hide.fade#linkModal{ tabindex: '-1', role: 'dialog', 'aria-labelledby' => 'myModalLabel',
  'aria-hidden' => true, style: 'display: none;' }

  = form_for([spoke, post]) do |f|
    .modal-header
      %button.close{ type: 'button', 'data-dismiss' => 'modal', 'aria-hidden' => true } x
      %h3 Add your link

    .modal-body
      - if post.errors.any?
        #error_explanation
          %h2
            = pluralize(post.errors.count, 'error')
            prohibited this post from being saved:

          %ul
            - post.errors.full_messages.each do |msg|
              %li= msg

      = f.text_field :title, placeholder: 'Post title', class: 'span4'
      = f.text_field :content, class: 'span4', placeholder: 'http://'

    .modal-footer
      %button.btn{ 'data-dismiss' => 'modal', 'aria-hidden' => 'true' } Cancel
      = f.submit 'Post', class: 'btn btn-primary'

app/views/spokes/_post_text_modal.html.haml
.modal.hide.fade#postModal{ tabindex: '-1', role: 'dialog', 'aria-labelledby' => 'myModalLabel',
  'aria-hidden' => true, style: 'display: none;' }

  = form_for([spoke, post]) do |f|
    .modal-header
      %button.close{ type: 'button', 'data-dismiss' => 'modal', 'aria-hidden' => true } x
      %h3 Add your post

    .modal-body
      - if post.errors.any?
        #error_explanation
          %h2
            = pluralize(post.errors.count, 'error')
            prohibited this post from being saved:

          %ul
            - post.errors.full_messages.each do |msg|
              %li= msg

      = f.text_field :title, placeholder: 'Post title', class: 'span5'
      %br
      = f.text_area :content, class: 'span5', placeholder: 'Post content'
      %script
        $(function () {
        $("#post-help").popover();
        });

      %a#post-help{ href: '#', rel: 'popover',
        'data-original-title' => 'stuff',
        'data-content' => html_rules_for_posting,
        'data-placement' => 'right' }
        %i.icon-question-sign

    .modal-footer
      %button.btn{ 'data-dismiss' => 'modal', 'aria-hidden' => 'true' } Cancel
      = f.submit 'Post', class: 'btn btn-primary'

app/views/spokes/_sort_options.html.haml
- Post.sort_options.each do |option|
  %li{ class: active_li? { option == sorter } }

    - if defined?(spoke_id) && spoke_id
      = link_to option.humanize, spoke_path(id: spoke_id, sort: option)

    - else
      = link_to option.humanize, home_path(sort: option)

app/views/spokes/_spoke_info.haml
.well
  %h2= spoke.name

  %p= spoke.description

  - if user_signed_in? && current_user.admin?
    = link_to 'Edit', edit_spoke_path(spoke), class: 'btn btn-mini btn-warning'