config/routes.rb
HubHub::Application.routes.draw do
  root 'home#index'

  get '/admin/sign_in', to: 'sessions#new', as: 'new_admin_session'
  post '/admin/sign_in', to: 'sessions#create', as: 'admin_sessions'
  delete '/admin/sign_out', to: 'sessions#destroy', as: 'destroy_admin_session'

  ActiveAdmin.routes(self)

  namespace :api, defaults: { format: 'json' } do
    resources :spokes, only: %i[index show]
    resources :posts, except: %i[new edit]
    resources :responses, except: %i[new edit]

    post '/sessions', to: 'sessions#create'
    delete '/sessions', to: 'sessions#destroy'

    resources :users, only: %i[create show update destroy]
  end
end

app/models/comment.rb
class Comment < ActiveRecord::Base
  attr_accessible :body

  belongs_to :commentable, polymorphic: true, counter_cache: :commentable_count
  belongs_to :user

  validates_presence_of :body
  validates_presence_of :user

  make_flaggable :inappropriate
  acts_as_nested_set :scope => [:commentable_id, :commentable_type]
  acts_as_votable

  scope :last_24_hours, where('created_at >= :twenty_four_hours_ago AND created_at < :now',
    twenty_four_hours_ago: (Time.now - 86400), now: Time.now)

  # Helper class method to lookup all comments assigned
  # to all commentable types for a given user.
  scope :find_comments_by_user, lambda { |user|
    where(:user_id => user.id).order('created_at DESC')
  }

  # Helper class method to look up all comments for
  # commentable class name and commentable id.
  scope :find_comments_for_commentable, lambda { |commentable_str, commentable_id|
    where(commentable_type: commentable_str.to_s, commentable_id: commentable_id).
      order('created_at DESC')
  }

  # Helper class method that allows you to build a comment
  # by passing a commentable object, a user_id, and comment text
  # example in readme
  def self.build_from(obj, user_id, comment)
    c = self.new
    c.commentable_id = obj.id
    c.commentable_type = obj.class.base_class.name
    c.body = comment
    c.user_id = user_id

    c
  end

  # Helper class method to look up a commentable object
  # given the commentable class name and id.
  def self.find_commentable(commentable_str, commentable_id)
    commentable_str.constantize.find(commentable_id)
  end

  # Gets the Post that the Comment is part of.
  def post
    Post.find(self.commentable_id)
  end

  def post_id
    Post.find(self.commentable_id).id
  end

  #helper method to check if a comment has children
  def has_children?
    self.children.size > 0
  end

  # @return [String] 'comment'
  def item_type
    self.class.to_s.downcase
  end

  def make_child_of(comment_id)
    parent_comment = Comment.find(comment_id.to_i)
    self.move_to_child_of(parent_comment)

    save
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  # Devise filter
  before_filter :authenticate_user!
  before_filter :ensure_admin, only: :destroy

  def create
    body = if params[:comment] && params[:comment][:body]
      params[:comment][:body]
    else ''
    end

    @post = Post.find(params[:post_id])
    @current_user = current_user
    @comment = Comment.build_from(@post, @current_user.id, body)

    if @comment.save
      flash[:notice] = 'Your response was added.'

      if params[:parent_type] == 'comment'
        parent_id = params[:parent_id]

        unless @comment.make_child_of(parent_id)
          logger.info "ERROR! Unable to make comment a child comment to ID #{parent_id}"
          flash[:error] = 'Unable to make response a child response.'
        end
      end
    else
      flash[:error] = @comment.errors.full_messages.join('; ')
    end

    redirect_to spoke_post_path(@post.spoke, @post)
  end

  def edit
    begin
      @comment = current_user.comments.find(params[:id])
    rescue ActiveRecord::RecordNotFound
      post = Post.find(params[:post_id])
      flash[:error] = 'You must have created the response to be able to edit it.'
      redirect_to spoke_post_path(post.spoke, post)
    end
  end

  def update
    begin
      @comment = current_user.comments.find(params[:id])
    rescue ActiveRecord::RecordNotFound
      post = Post.find(params[:post_id])
      flash[:error] = 'You must have created the response to be able to update it.'
      redirect_to spoke_post_url(post.spoke, post)

      return
    end

    if @comment.update_attributes(params[:comment])
      post = @comment.post
      flash[:notice] = 'Response was successfully updated.'
      redirect_to spoke_post_path(post.spoke, post)
    else
      render 'edit'
    end
  end

  def destroy
    @comment = Comment.find(params[:id])

    if params[:disable] == 'true'
      flash[:notice] = "Disabled response #{@comment.id}"
      @comment.destroy
    elsif params[:disable] == 'false'
      flash[:notice] = "Revived response #{@comment.id}"
      @comment.revive
    end

    respond_to do |format|
      format.js
    end
  end

  def flag
    @comment = Comment.find(params[:comment_id])

    if params[:flag_type]
      current_user.toggle_flag(@comment, params[:flag_type])
    end

    respond_to do |format|
      format.js
    end
  end
end

app/views/comments/_comment.html.haml
%tr{ id: "comment-#{comment.id}" }
  %td
    = render partial: 'shared/votable_item', locals: { votable_item: comment }
    = render partial: 'comments/inappropriate_comment', locals: { inappropriate_comment: comment }
    - if user_signed_in? && current_user.admin?
      = render 'comments/disable_comment', disable_comment: comment

  %td.comment
    .pull-right
      = link_to spoke_post_url(comment.post.spoke_id, comment.post.id,
        anchor: "comment-#{comment.id}") do
        %i.icon-magnet
    %p
      added
      = time_tag comment.created_at
      by
      %b= comment.user.name

      - if comment.user == current_user
        = link_to 'Edit',
          edit_spoke_post_comment_path(comment.post.spoke_id, comment.post.id, comment),
          class: 'btn btn-mini btn-warning'

      - if user_signed_in? && !comment.deleted?
        %a.btn.btn-mini{ href: '#', 'data-target' => "#comment-reply-#{comment.id}",
          title: 'Reply to response', 'data-toggle' => 'collapse' }
          reply
        .collapse{ id: "comment-reply-#{comment.id}" }
          = render 'comments/new', parent_type: 'comment', parent_id: comment.id,
            post: comment.post, comment: Comment.new

      - else
        %a.btn.btn-mini.disabled{ href: '#', title: 'Reply to response' }
          reply

    - if comment.deleted?
      - if user_signed_in? && current_user == comment.user || current_user.admin?
        %strong
          .label.label-important= disabled_item_message_for_owner('comment')
        %p= Sanitize.clean(comment.body, Sanitize::Config::BASIC)

      - else
        %p
          %strong
            .label.label-warning= disabled_item_message('comment')

    - else
      %p= Sanitize.clean(comment.body, Sanitize::Config::BASIC)

    - if comment.has_children?
      %table.table.table-condensed.table-striped
        %tbody
          = render partial: 'comments/comment', collection: comment.children

app/views/comments/_disable_comment.html.haml
= form_tag(spoke_post_comment_path(disable_comment.post.spoke_id, disable_comment.post.id, disable_comment.id),
  class: 'form-horizontal', method: :delete, remote: true) do
  = hidden_field_tag "disable", !disable_comment.deleted?

  - if disable_comment.deleted?
    = button_tag type: 'submit',
      class: 'btn btn-mini btn-danger',
      id: "disable-comment-#{disable_comment.id}",
      title: 'This response has been disabled.' do
      %i.icon-remove-sign.pull-left

  - else
    = button_tag type: 'submit',
      class: 'btn btn-mini',
      id: "disable-comment-#{disable_comment.id}",
      title: 'This response is enabled.' do
      %i.icon-remove-sign.pull-left

app/views/comments/_form.html.haml
= form_for(comment, url: spoke_post_comment_path, html: { class: 'form-horizontal' }) do |f|
  - if comment.errors.any?
    #error_explanation
      %h2
        = pluralize(comment.errors.count, 'error')
        prohibited this response from being saved:

      %ul
        - comment.errors.full_messages.each do |msg|
          %li= msg

  %fieldset
    .control-group
      = f.label :body, class: 'control-label'
      .controls
        = f.text_area :body, class: 'span5'

  .form-actions
    = f.submit 'Update', class: 'btn btn-primary'
    = link_to 'Cancel', spoke_post_path(comment.post.spoke_id, comment.post.id),
      class: 'btn btn-danger'

app/views/comments/_inappropriate_comment.html.haml
- if user_signed_in? && !inappropriate_comment.deleted?
  = form_tag(spoke_post_comment_flag_path(inappropriate_comment.post.spoke_id,
    inappropriate_comment.post.id, inappropriate_comment.id),
    class: 'form-horizontal', method: :put, remote: true) do
    = hidden_field_tag :id, inappropriate_comment.id
    = hidden_field_tag :flag_type, :inappropriate

    - if current_user.flagged?(inappropriate_comment, :inappropriate)
      = button_tag type: 'submit',
        class: 'btn btn-mini btn-danger',
        id: "inappropriate-comment-#{inappropriate_comment.id}",
        title: 'You have flagged this response as inappropriate.' do
        %i.icon-warning-sign.pull-left

    - elsif inappropriate_comment.flagged?(:inappropriate)
      = button_tag type: 'submit',
        class: 'btn btn-mini btn-warning',
        id: "inappropriate-comment-#{inappropriate_comment.id}",
        title: 'Someone else has flagged this response as inappropriate.' do
        %i.icon-warning-sign.pull-left

    - else
      = button_tag type: 'submit',
        class: 'btn btn-mini',
        id: "inappropriate-comment-#{inappropriate_comment.id}" do
        %i.icon-warning-sign.pull-left

- else
  - if inappropriate_comment.flagged?(:inappropriate)
    = button_tag type: 'submit',
      class: 'btn btn-mini btn-warning disabled',
      title: 'Someone else has flagged this response as inappropriate.' do
      %i.icon-warning-sign.pull-left

  - else
    %p
      %button.btn.btn-mini.disabled
        %i.icon-warning-sign

app/views/comments/_new.html.haml
= form_for([post.spoke, post, comment], html: { class: 'well' }) do |f|
  - if comment.errors.any?
    #error_explanation
      %h2
        = pluralize(comment.errors.count, 'error')
        prohibited this comment from being saved:

      %ul
        - comment.errors.full_messages.each do |msg|
          %li= msg

  %fieldset
    .control-group
      .controls
        = f.text_area :body, class: 'comment'

    = hidden_field_tag 'parent_type', parent_type

    = hidden_field_tag 'parent_id', parent_id

    - if user_signed_in?
      = f.submit 'Respond', class: 'btn btn-primary'
    - else
      %script
        $(function () {
        $("#post-save-button").popover();
        });
      %button.btn.btn-primary.disabled#post-save-button{ rel: 'popover',
        'data-content' => 'Login to post!', 'data-original-title' => 'Login' } Response

app/views/comments/destroy.js.erb
<% if @comment.deleted? %>
$('#disable-comment-<%= @comment.id %>').addClass('btn-danger');
<% else %>
$('#disable-comment-<%= @comment.id %>').removeClass('btn-danger');
<% end %>

app/views/comments/edit.html.haml
%h1 Editing post

.row
  .span9
    = render 'form', comment: @comment

app/views/comments/flag.js.erb
<% if current_user.flagged?(@comment, :inappropriate) %>
$('#inappropriate-comment-<%= @comment.id %>').addClass('btn-danger');
$('#inappropriate-comment-<%= @comment.id %>').removeClass('btn-warning');
$('#inappropriateFlag').modal('show');
<% elsif @comment.flagged?(:inappropriate) %>
$('#inappropriate-comment-<%= @comment.id %>').removeClass('btn-danger');
$('#inappropriate-comment-<%= @comment.id %>').addClass('btn-warning');
<% else %>
$('#inappropriate-comment-<%= @comment.id %>').removeClass('btn-danger');
$('#inappropriate-comment-<%= @comment.id %>').removeClass('btn-warning');
<% end %>

app/views/comments/update.js.erb
<% if current_user.flagged?(@comment, :inappropriate) %>
$('#inappropriate-comment-<%= @comment.id %>').addClass('btn-danger')
$('#inappropriate-comment-<%= @comment.id %>').removeClass('btn-warning')
$('#inappropriateFlag').modal('show')
<% elsif @comment.flagged?(:inappropriate) %>
$('#inappropriate-comment-<%= @comment.id %>').removeClass('btn-danger')
$('#inappropriate-comment-<%= @comment.id %>').addClass('btn-warning')
<% else %>
$('#inappropriate-comment-<%= @comment.id %>').removeClass('btn-danger')
$('#inappropriate-comment-<%= @comment.id %>').removeClass('btn-warning')
<% end %>