config/routes.rb
HubHub::Application.routes.draw do
  root 'home#index'

  get '/admin/sign_in', to: 'sessions#new', as: 'new_admin_session'
  post '/admin/sign_in', to: 'sessions#create', as: 'admin_sessions'
  delete '/admin/sign_out', to: 'sessions#destroy', as: 'destroy_admin_session'

  ActiveAdmin.routes(self)

  namespace :api, defaults: { format: 'json' } do
    resources :spokes, only: %i[index show]
    resources :posts, except: %i[new edit]
    resources :responses, except: %i[new edit]

    post '/sessions', to: 'sessions#create'
    delete '/sessions', to: 'sessions#destroy'

    resources :users, only: %i[create show update destroy]
  end
end

app/views/admin/edit_digest_email_settings.html.haml
= form_tag(admin_update_digest_email_settings_path(setting: :send_time),
  method: :put, class: 'form-horizontal') do
  %fieldset.control-group
    = label_tag :send_time, "Daily send time", class: 'control-label'
    .controls
      = text_field_tag :send_time, @send_time

  .form-actions.devise-form-button
    = submit_tag "Update", class: 'btn btn-primary'

app/views/admin/inappropriate_items.html.haml
%table.table.table-condensed.table-striped
  %thead
    %caption
      %h3 Flagged posts and comments
    %tr
      %th Title
      %th Author
      %th Flagger
      %th Flagged On
  %tbody
  - @flags_and_posts.each do |fp|
    %tr
      %td
        = fp[:title]
      %td
        = fp[:poster]
      %td
        = fp[:flagger]
      %td
        = time_tag fp[:flag_date]

app/views/admin/index_users.html.haml
%table.table.table-condensed.table-striped
  %thead
    %caption
      %h3 Users

    %tr
      %th Email
      %th First
      %th Last
      %th Admin?
      %th Banned?

  %tbody
    - @users.each do |u|
      %tr
        %td= link_to u.email, admin_user_path(u.id)
        %td= u.first_name
        %td= u.last_name
        %td
          = render partial: 'admin/admin_checkbox', locals: { user: u }
        %td
          = render partial: 'admin/banned_checkbox', locals: { user: u }

app/views/admin/show_user.html.haml
.page-title
  %h1
    = @user.email

%table.table.table-striped.table-bordered
  %thead
  %tbody
    %tr
      %td
        %strong First Name
      %td
        = @user.first_name

    %tr
      %td
        %strong Last Name
      %td
        = @user.last_name

    %tr
      %td
        %strong Sign-in Count
      %td
        = @user.sign_in_count

    %tr
      %td
        %strong Last sign-in at
      %td
        - if @user.last_sign_in_at
          = time_tag @user.last_sign_in_at
        - else
          \-

    %tr
      %td
        %strong Last sign-in IP
      %td
        - if @user.last_sign_in_ip
          = @user.last_sign_in_ip
        - else
          \-

    %tr
      %td
        %strong Admin?
      %td
        = render partial: 'admin/admin_checkbox', locals: { user: @user }

    %tr
      %td
        %strong Banned?
      %td
        = render partial: 'admin/banned_checkbox', locals: { user: @user }

%p
  = link_to :back do
    %button.btn
      %i.icon-backward
      Back

app/views/admin/update_digest_email_settings.html.haml
= form_tag(admin_update_digest_email_settings_path(setting: :send_time),
  method: :put, class: 'form-horizontal') do
  %fieldset.control-group
    = label_tag :send_time, "Daily send time", class: 'control-label'
    .controls
      = text_field_tag :send_time, @send_time

  .form-actions.devise-form-button
    = submit_tag "Update", class: 'btn btn-primary'

app/views/admin/update_user_admin.js.erb
$('#admin-<%= @user.id %>').parent().css({'backgroundColor':'#99cc33'}).
  animate({'backgroundColor':'#fff'}, 1500, "linear", function()
    {
          $('#admin-<%= @user.id %>').parent().css({'backgroundColor':''})
    });

app/views/admin/update_user_ban.js.erb
$('#ban-<%= @user.id %>').parent().css({'backgroundColor':'#99cc33'}).
  animate({'backgroundColor':'#fff'}, 1500, "linear", function()
    {
          $('#ban-<%= @user.id %>').parent().css({'backgroundColor':''})
    });

app/views/admin/user.html.haml
.page-title
  %h1
    = @user.email

%table.table.table-striped.table-bordered
  %thead
  %tbody
    %tr
      %td
        %strong First Name
      %td
        = @user.first_name
    %tr
      %td
        %strong Last Name
      %td
        = @user.last_name
    %tr
      %td
        %strong Sign-in Count
      %td
        = @user.sign_in_count
    %tr
      %td
        %strong Last sign-in at
      %td
        = time_tag @user.last_sign_in_at
    %tr
      %td
        %strong Last sign-in IP
      %td
        = @user.last_sign_in_ip

%p
  = link_to :back do
    %button.btn
      %i.icon-backward
      Back

app/views/admin/users.html.haml
%table.table.table-condensed.table-striped
  %thead
    %caption
      %h3 Users
    %tr
      %th Email
      %th First
      %th Last
      %th Admin?
  %tbody
    - @users.each do |u|
      %tr
        %td= link_to u.email, admin_user_path(u.id)
        %td= u.first_name
        %td= u.last_name
        %td
          - if u.email == "admin@mindhub.org"
            = check_box_tag 'is_admin', !u.admin?, u.admin?, id: u.id,
              disabled: true

          - else
            = form_tag(user_path(u), method: :put, remote: true) do
              = check_box_tag 'is_admin', !u.admin?, u.admin?, id: u.id,
                class: "confirm-selection checkable"